//Generated By Amr Awwad
const express = require("express");

const {
  createBlog,
  getBlogs,
  getBlog,
  updateBlog,
  deleteBlog,
} = require("../services/blogService");
const {
  getBlogValidator,
  createBlogValidator,
  updateBlogValidator,
  deleteBlogValidator,
} = require("../utils/validators/blogValidator");
const subblogsRoute = require("./subBlogRoute");

const authService = require("../services/authService");

const router = express.Router();

// router.post('/', createBlog);
// router.get('/', getBlogs);
// router.get('/:id', getBlog);
// router.put('/:id', updateBlog);
// router.delete('/:id', deleteBlog);
router.use("/:blogId/subblogs", subblogsRoute);
router
  .route("/")
  .get(getBlogs)
  .post(authService.protect, createBlogValidator, createBlog);
router
  .route("/:id")
  .get(getBlogValidator, getBlog)
  .put(authService.protect, updateBlogValidator, updateBlog)
  .delete(authService.protect, deleteBlogValidator, deleteBlog);
// router.route('/').post(createBlog);
module.exports = router;
