//Generated By Amr Awwad
const express = require("express");

const {
  createCustomer,
  getCustomers,
  getCustomer,
  createProduct,
  updateCustomer,
  deleteCustomer,
} = require("../services/customerService");
const {
  getCustomerValidator,
  createCustomerValidator,
  updateCustomerValidator,
  deleteCustomerValidator,
} = require("../utils/validators/customerValidator");

const authService = require("../services/authService");

const router = express.Router();

router
  .route("/")
  .get(getCustomers)
  .post(authService.protect, createCustomerValidator, createCustomer);
router
  .route("/:id")
  .get(getCustomer)
  .put(authService.protect, updateCustomerValidator, updateCustomer)
  .delete(authService.protect, deleteCustomerValidator, deleteCustomer);
router.route("/product").post(createProduct);
module.exports = router;
