//Generated By Amr Awwad
const express = require("express");

const {
  createFeature,
  getFeatures,
  getFeature,
  updateFeature,
  deleteFeature,
  addFeatureToProduct,
} = require("../services/FeatureService");
const {
  getFeatureValidator,
  createFeatureValidator,
  addFeatureToProductValidator,
  updateFeatureValidator,
  deleteFeatureValidator,
} = require("../utils/validators/featureValidator");

const authService = require("../services/authService");

const router = express.Router();

router
  .route("/")
  .get(getFeatures)
  .post(authService.protect, createFeatureValidator, createFeature);
  
  router
  .route("/addFeatureToProduct")
  .post(authService.protect, addFeatureToProductValidator, addFeatureToProduct);

router
  .route("/:id")
  .get(getFeature)
  .put(authService.protect, updateFeatureValidator, updateFeature)
  .delete(authService.protect, deleteFeatureValidator, deleteFeature);
module.exports = router;
