//Generated By Amr Awwad
const express = require("express");

const {
  createPlan,
  getPlans,
  getPlan,
  updatePlan,
  deletePlan,
} = require("../services/PlanService");
const {
  getPlanValidator,
  createPlanValidator,
  updatePlanValidator,
  deletePlanValidator,
} = require("../utils/validators/planValidator");

const authService = require("../services/authService");

const router = express.Router();

router
  .route("/")
  .get(getPlans)
  .post(authService.protect,  createPlan);
router
  .route("/:id")
  .get(getPlan)
  .put(authService.protect, updatePlanValidator, updatePlan)
  .delete(authService.protect, deletePlanValidator, deletePlan);
module.exports = router;
