//Generated By Amr Awwad
const express = require("express");

const {
  createProduct,
  getProducts,
  getProduct,
  updateProduct,
  deleteProduct,
} = require("../services/ProductService");
const {
  getProductValidator,
  createProductValidator,
  updateProductValidator,
  deleteProductValidator,
} = require("../utils/validators/productValidator");

const authService = require("../services/authService");

const router = express.Router();

router
  .route("/")
  .get(getProducts)
  .post(authService.protect, createProductValidator, createProduct);
router
  .route("/:id")
  .get(getProduct)
  .put(authService.protect, updateProductValidator, updateProduct)
  .delete(authService.protect, deleteProductValidator, deleteProduct);
module.exports = router;
