//Generated By Amr Awwad
const express = require("express");

const {
  createSubscription,
  getSubscriptions,
  getSubscription,
  updateSubscription,
  deleteSubscription,
} = require("../services/SubscriptionService");
const {
  getSubscriptionValidator,
  createSubscriptionValidator,
  updateSubscriptionValidator,
  deleteSubscriptionValidator,
} = require("../utils/validators/subscriptionValidator");

const authService = require("../services/authService");

const router = express.Router();

router
  .route("/")
  .get(getSubscriptions)
  .post(authService.protect, createSubscriptionValidator, createSubscription);
router
  .route("/:id")
  .get(getSubscription)
  .put(authService.protect, updateSubscriptionValidator, updateSubscription)
  .delete(authService.protect, deleteSubscriptionValidator, deleteSubscription);
module.exports = router;
