//Generated By Amr Awwad
const { check } = require("express-validator");
const validatorMiddleware = require("../../middlewares/validatorMiddleware");

exports.getCustomerValidator = [
  check("id").isMongoId().withMessage("Invalid customer id format"),
  validatorMiddleware,
];

exports.createCustomerValidator = [
  check("name")
    .notEmpty()
    .withMessage("Customer required")
    .isLength({ min: 2 })
    .withMessage("Too short customer name")
    .isLength({ max: 32 })
    .withMessage("Too long customer name"),
  validatorMiddleware,

  check("email")
    .notEmpty()
    .withMessage("Email required")
    .isEmail()
    .withMessage("Invalid email address")
    .custom((val) =>
      User.findOne({ email: val }).then((user) => {
        if (user) {
          return Promise.reject(new Error("E-mail already in user"));
        }
      })
    ),

  check("phone")
    .optional()
    .isMobilePhone(["ar-EG", "ar-SA"])
    .withMessage("Invalid phone number only accepted Egy and SA Phone numbers"),
];

exports.updateCustomerValidator = [
  check("id").isMongoId().withMessage("Invalid customer id format"),
  validatorMiddleware,
];

exports.deleteCustomerValidator = [
  check("id").isMongoId().withMessage("Invalid customer id format"),
  validatorMiddleware,
];
