//Generated By Amr Awwad
const { check } = require("express-validator");
const validatorMiddleware = require("../../middlewares/validatorMiddleware");

exports.getFeatureValidator = [
  check("id").isMongoId().withMessage("Invalid feature id format"),
  validatorMiddleware,
];

exports.createFeatureValidator = [
  check("name")
    .notEmpty()
    .withMessage("name required")
    .isLength({ min: 2 })
    .withMessage("Too short feature name")
    .isLength({ max: 32 })
    .withMessage("Too long feature name"),
  validatorMiddleware,

  check("lookup_key")
    .notEmpty()
    .withMessage("lookup_key required")
];

exports.addFeatureToProductValidator = [
  check("featureId")
    .notEmpty()
    .withMessage("featureId required"),
  validatorMiddleware,

  check("productId")
    .notEmpty()
    .withMessage("productId required")
];

exports.updateFeatureValidator = [
  check("name")
    .notEmpty()
    .withMessage("Feature required")
    .isLength({ min: 2 })
    .withMessage("Too short feature name")
    .isLength({ max: 32 })
    .withMessage("Too long feature name"),
  validatorMiddleware,

  check("email")
    .notEmpty()
    .withMessage("Email required")
    .isEmail()
    .withMessage("Invalid email address")
    .custom((val) =>
      User.findOne({ email: val }).then((user) => {
        if (user) {
          return Promise.reject(new Error("E-mail already in user"));
        }
      })
    ),

  check("phone")
    .optional()
    .isMobilePhone(["ar-EG", "ar-SA"])
    .withMessage("Invalid phone number only accepted Egy and SA Phone numbers"),
];

exports.deleteFeatureValidator = [
  check("id").isMongoId().withMessage("Invalid feature id format"),
  validatorMiddleware,
];
