//Generated By Amr Awwad
const { check } = require("express-validator");
const validatorMiddleware = require("../../middlewares/validatorMiddleware");

exports.getPlanValidator = [
  check("id").isMongoId().withMessage("Invalid plan id format"),
  validatorMiddleware,
];

exports.createPlanValidator = [
  check("nickname")
    .notEmpty()
    .withMessage("nickname required"),
  validatorMiddleware,

  check("amount")
    .notEmpty()
    .withMessage("amount required"),
  validatorMiddleware,

  check("interval")
    .notEmpty()
    .withMessage("interval required"),
  validatorMiddleware,

  check("currency")
    .notEmpty()
    .withMessage("currency required"),
  validatorMiddleware,

  check("product")
    .notEmpty()
    .withMessage("product required"),
  validatorMiddleware,

];

exports.updatePlanValidator = [
  check("name")
    .notEmpty()
    .withMessage("Plan required")
    .isLength({ min: 2 })
    .withMessage("Too short plan name")
    .isLength({ max: 32 })
    .withMessage("Too long plan name"),
  validatorMiddleware,

  check("email")
    .notEmpty()
    .withMessage("Email required")
    .isEmail()
    .withMessage("Invalid email address")
    .custom((val) =>
      User.findOne({ email: val }).then((user) => {
        if (user) {
          return Promise.reject(new Error("E-mail already in user"));
        }
      })
    ),

  check("phone")
    .optional()
    .isMobilePhone(["ar-EG", "ar-SA"])
    .withMessage("Invalid phone number only accepted Egy and SA Phone numbers"),
];

exports.deletePlanValidator = [
  check("id").isMongoId().withMessage("Invalid plan id format"),
  validatorMiddleware,
];
