//Generated By Amr Awwad
const { check } = require("express-validator");
const validatorMiddleware = require("../../middlewares/validatorMiddleware");

exports.getSubscriptionValidator = [
  check("id").isMongoId().withMessage("Invalid subscription id format"),
  validatorMiddleware,
];

exports.createSubscriptionValidator = [
  check("number")
    .notEmpty()
    .withMessage("number required"),
  validatorMiddleware,

  check("exp_month")
    .notEmpty()
    .withMessage("exp_month required"),
  validatorMiddleware,

  check("exp_year")
    .notEmpty()
    .withMessage("exp_month required"),
  validatorMiddleware,

  check("cvc")
    .notEmpty()
    .withMessage("exp_month required"),
  validatorMiddleware,

];

exports.updateSubscriptionValidator = [
  check("name")
    .notEmpty()
    .withMessage("Subscription required")
    .isLength({ min: 2 })
    .withMessage("Too short subscription name")
    .isLength({ max: 32 })
    .withMessage("Too long subscription name"),
  validatorMiddleware,

  check("email")
    .notEmpty()
    .withMessage("Email required")
    .isEmail()
    .withMessage("Invalid email address")
    .custom((val) =>
      User.findOne({ email: val }).then((user) => {
        if (user) {
          return Promise.reject(new Error("E-mail already in user"));
        }
      })
    ),

  check("phone")
    .optional()
    .isMobilePhone(["ar-EG", "ar-SA"])
    .withMessage("Invalid phone number only accepted Egy and SA Phone numbers"),
];

exports.deleteSubscriptionValidator = [
  check("id").isMongoId().withMessage("Invalid subscription id format"),
  validatorMiddleware,
];
