//Generated By Amr Awwad

// seeders/admin-seeder.js
const mongoose = require("mongoose");
// const bcrypt = require("bcryptjs");
const User = require("../models/userModel");

async function seedAdmin() {
  await mongoose.connect("mongodb://localhost:27017/mydb", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  // Check if admin already exists
  const existingAdmin = await User.findOne({ role: "admin" });
  console.log(existingAdmin);
  if (!existingAdmin) {
    // Create admin credentials
    const adminCredentials = {
      name: "Admin User",
      email: "admin@gmail.com",
      password: "adminpassword",
      phone: "01557011198",
      role: "admin",
    };

    // Create admin user
    await User.create(adminCredentials);

    console.log("Admin user created successfully");
  } else {
    console.log("Admin user already exists");
  }

  await mongoose.disconnect();
}

// Execute the admin seeder
seedAdmin()
  .then(() => {
    console.log("Admin seeding completed");
    process.exit(0);
  })
  .catch((err) => {
    console.error("Error seeding admin:", err);
    process.exit(1);
  });
