//Generated By Amr Awwad
const mongoose = require("mongoose");

const featureSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      trim: true,
      required: [true, "name required"],
    },
    lookup_key: {
      type: String,
      required: [true, "lookup_key required"],
    },
  },
  { timestamps: true }
);

const FeatureModel = mongoose.model("Feature", featureSchema);
module.exports = FeatureModel;
