//Generated By Amr Awwad
const mongoose = require("mongoose");

const planSchema = new mongoose.Schema(
  {
    nickname: {
      type: String,
      trim: true,
      required: [true, "number required"],
    },
    
    amount: {
      type: Number,
      trim: true,
      required: [true, "exp_month required"],
    },
    
    interval: {
      type: String,
      trim: true,
      required: [true, "number required"],
    },
    
    currency: {
      type: String,
      trim: true,
      required: [true, "number required"],
    },
    
    product: {
      type: String,
      trim: true,
      required: [true, "number required"],
    },
    
    stripeID: {
      type: String
    },
  },
  { timestamps: true }
);

const PlanModel = mongoose.model("Plan", planSchema);
module.exports = PlanModel;
