//Generated By Amr Awwad
const mongoose = require("mongoose");


const priceSchema = new mongoose.Schema(
  {
    unit_amount: {
      type: Number,
      trim: true,
      required: [true, "unit_amount required"],
    },
    currency: {
      type: String,
      required: [true, "currency required"],
      lowercase: true,
    },
    recurring: {
      type: Object,
      required: [true, "recurring required"],
    },
    product: {
      type: String,
      required: [true, "product required"],
    },
  },
  { timestamps: true }
);

const PriceModel = mongoose.model("Price", priceSchema);
module.exports = PriceModel;
