//Generated By Amr Awwad
const mongoose = require("mongoose");

const subscriptionSchema = new mongoose.Schema(
  {
    number: {
      type: Number,
      trim: true,
      required: [true, "number required"],
    },
    
    exp_month: {
      type: Number,
      trim: true,
      required: [true, "exp_month required"],
    },
    
    exp_year: {
      type: Number,
      trim: true,
      required: [true, "exp_year required"],
    },
    
    cvc: {
      type: Number,
      trim: true,
      required: [true, "cvc required"],
    },
    
    stripeID: {
      type: String
    },
  },
  { timestamps: true }
);

const SubscriptionModel = mongoose.model("Subscription", subscriptionSchema);
module.exports = SubscriptionModel;
